DELETE http://localhost:3001/api/persons/62b325cd7af3886876928cf8

###

POST http://localhost:3001/api/persons
Content-Type:application/json

{
    "name":"Anna Montanas",
    "number":"123-456-789"
}
###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/62b2d63849b0c06355a86ef9

###
GET http://localhost:3001/api/whatever

###
PUT http://localhost:3001/api/persons/62b2d63849b0c06355a86ef9
Content-Type:application/json

{
    "name":"Ken Man",
    "number":"123-456-789-212"
}