DELETE http://localhost:3001/api/persons/qwtt

###

POST http://localhost:3001/api/persons
Content-Type:application/json

{
    "name":"Buzzd Lightyear",
    "number":"123-456-789"
}
###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/whatever

###
PUT http://localhost:3001/api/persons/62b2d63849b0c06355a86ef9
Content-Type:application/json

{
    "name":"Buzzd Lightyear",
    "number":"123-456-789-212"
}